version: "3"

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=clockshop
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - clockshop-net
  clockshop-service:
    image: clockshop/clockshop:1.0
    environment:
      - BOT_TOKEN=1983895587:AAFRWEbV_HWhMRozu52TH94G5lyYSyQcitY
      - POSTGRES_PATH=jdbc:postgresql://db:5432/clockshop
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_USERNAME=postgre

    networks:
      - clockshop-net
volumes:
  postgresql:
  postgresql_data:
    driver: local

networks:
  clockshop-net:
    driver:
       bridge
