spring:
  datasource:
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5432/clockshop}
    password: ${POSTGRES_PASSWORD:Vg31072001}
    username: ${POSTGRES_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver